web:
  build: .
  volumes:
    - "./modules:/app/modules"
    - "./themes:/app/themes"
  ports:
    - "8082:80"
  environment:
    - ALLOW_OVERRIDE=true
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal8
