web:
  build: .
  volumes:
    - "./themes:/app/wp-content/themes"
    - "./plugins:/app/wp-content/plugins"
  ports:
    - "8082:80"
  environment:
    - ALLOW_OVERRIDE=true
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=wordpress
