web:
  image: kevincoyle/drupal8
  volumes:
    - "./modules:/app/sites/all/modules"
    - "./themes:/app/sites/all/themes"
  ports:
    - "8082:80"
  environment:
    - ALLOW_OVERRIDE=true
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal7
